name: AWS Deploy

# Controls when the workflow will run
on:
  workflow_run:
        workflows: ['Build and Push Image']
        types: [completed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: Production
    steps:
      - name: Delete and Redeploy K8S
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.AWS_SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.AWS_SSH_USER }} # User of the server you want to ssh into
          
          script: |
              echo '--REDEPLOYING K8S--'
              kubectl delete deploy akairo
              kubectl apply -f deploy.yaml
              echo '--END OF REDEPLOY--'