# This is a basic workflow to help you get started with Actions

name: DigitalOcean Build and Publish Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.LOGIN_TOKEN }}
      GPT_API: ${{ secrets.GPT_API }}
    environment: Production
    steps:
      - name: Update Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
            echo '--PULLING REPO--'
            cd ~/bots/lenny
            git pull https://github.com/jkl2k2/lenny.git
            echo '--END OF PULL--'
      
      - name: Build Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
              echo '--BUILDING DOCKER IMAGE--'
              cd ~/bots/lenny/src
              rm -f .env
              touch .env
              echo TOKEN=${{ secrets.LOGIN_TOKEN }} >> .env
              echo GPT_API=${{ secrets.GPT_API }} >> .env

              cd ~/bots/lenny/
              docker build . -t ghcr.io/jkl2k2/lennyalpha-main
              echo '--END OF BUILD--'

      - name: Push Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
              echo '--PUSHING DOCKER IMAGE--'
              cd ~/bots/lenny
              docker push ghcr.io/jkl2k2/lennyalpha-main:latest
              echo '--END OF PUSHING--'