name: Build and Push Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cd src
          touch .env
          echo TOKEN=${{ secrets.LOGIN_TOKEN }} >> .env
          echo GPT_API=${{ secrets.GPT_API }} >> .env

      - name: Build Image
        run:
          docker build . -t ghcr.io/jkl2k2/lennyalpha-main:latest
    
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run:
          docker push ghcr.io/jkl2k2/lennyalpha-main:latest
